/**
 * Regenerates src/generated/burmese-dict.ts from ICU's Burmese
 * break-dictionary word list (icu4c/source/data/brkitr/dictionaries/
 * burmesedict.txt) at a pinned ICU tag.
 *
 * The generated word list is Unicode/ICU data, redistributed under the
 * Unicode License v3 (see the generated file header).
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ICU_TAG = 'release-77-1'
const URL = `https://raw.githubusercontent.com/unicode-org/icu/${ICU_TAG}/icu4c/source/data/brkitr/dictionaries/burmesedict.txt`

const response = await fetch(URL)
if (!response.ok) throw new Error(`Fetch failed: ${String(response.status)} ${URL}`)
const text = await response.text()

const words = new Set<string>()
for (const rawLine of text.split('\n')) {
  const line = (rawLine.split('#')[0] ?? '').trim()
  if (line === '') continue
  const word = (line.split('\t')[0] ?? '').trim()
  if (word !== '') words.add(word)
}

const sorted = [...words].sort()

// Prefix-delta encoding: each line stores the length of the prefix shared
// with the previous word (as a single ASCII character, '0' + length) followed
// by the remaining suffix.
const encoded = []
let previous = ''
for (const word of sorted) {
  let p = 0
  const max = Math.min(previous.length, word.length, 40)
  while (p < max && previous[p] === word[p]) p++
  encoded.push(String.fromCharCode(48 + p) + word.slice(p))
  previous = word
}

const header = `// Generated by scripts/build-burmese-dict.ts -- do not edit.
/*!
 * Burmese break-dictionary word list from ICU (${ICU_TAG}),
 * icu4c/source/data/brkitr/dictionaries/burmesedict.txt.
 * Copyright © 2016 and later Unicode, Inc. and others.
 * Licensed under the Unicode License v3 (SPDX-License-Identifier: Unicode-3.0);
 * see https://www.unicode.org/license.txt
 */
// ${String(sorted.length)} words, prefix-delta encoded: each line is
// (charCode - 48) shared prefix characters from the previous word, then the
// suffix.

const encoded: string = ${JSON.stringify(encoded.join('\n'))}

export default encoded
`

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'generated', 'burmese-dict.ts')
writeFileSync(out, header)
console.log(`Wrote ${out}: ${String(sorted.length)} words, ${String(header.length)} bytes`)
